# Herramientas python para ciencia de los datos

## Ejercicios de Numpy

In [1]:
import numpy as np

In [1]:
import numpy as np

# Multiplicación de matrices
A = np.array( [[3, 1, 2], 
               [4, 1, 9], 
               [9, 8, 6], 
               [3, 5, 1]])
B= np.array([0, 2, 1, 3])
C= np.array([2, -1, 0])
result_matrix = np.dot(B, A)
print("Resultado de la multiplicación de matrices:")
print(result_matrix)

# Producto escalar de dos vectores
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result_scalar = np.dot(x, y)
print("\nResultado del producto escalar:")
print(result_scalar)
np.mean(A,axis=0)


Resultado de la multiplicación de matrices:
[26 25 27]

Resultado del producto escalar:
32


array([[3, 4, 9, 3],
       [1, 1, 8, 5],
       [2, 9, 6, 1]])

In [22]:
A[B,[True, False, False]]

array([3, 9, 4, 3])

In [27]:
np.mean(A,axis=1)

array([2.        , 4.66666667, 7.66666667, 3.        ])

#### Ejercicio 1

Generar una matrix aleatoria 3x4 y normalizar sus componentes (trasladándolos y escalándolos) de manera que el menor sea 0 y el mayor 1.

In [ ]:
# Ejemplo:

# array original:

# array([[ 1,  4, -4, -4],
#        [ 4,  1, -5,  1],
#        [ 2, -3,  0, -4]]

# array normalizado
# array([[0.66666667, 1.        , 0.11111111, 0.11111111],
#        [1.        , 0.66666667, 0.        , 0.66666667],
#        [0.77777778, 0.22222222, 0.55555556, 0.11111111]])

m = np.random.randn(3,4)



maximo = m.max()
minimo = m.min()
normalizada = (m-minimo) / (maximo - minimo)
m,normalizada




#### Ejercicio 2

Construir una matriz 3x4 cuyas tres filas son los elementos del 0 al 3

In [ ]:
#### Ejemplo:
#array([[0., 1., 2., 3.],
#       [0., 1., 2., 3.],
#       [0., 1., 2., 3.]])

a = np.empty([3,4])
a[:]=np.arange(4)



In [ ]:
a

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

#### Ejercicio 3

En una matriz 20x20, obtener la matriz que se obtiene al extraer las filas de índice par y las columnas de índice impar.

In [ ]:

A = np.arange(400).reshape(20,20)
A[::2, 1::2]





array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
       [201, 203, 205, 207, 209, 211, 213, 215, 217, 219],
       [241, 243, 245, 247, 249, 251, 253, 255, 257, 259],
       [281, 283, 285, 287, 289, 291, 293, 295, 297, 299],
       [321, 323, 325, 327, 329, 331, 333, 335, 337, 339],
       [361, 363, 365, 367, 369, 371, 373, 375, 377, 379]])

#### Ejercicio 4

Dada una matriz A de tamaño 10x4 y otra B de tamaño 10x1 con valores entre 0 y 100, devolver una matriz conteniendo las filas que corresponden a las posiciones de B que son mayores de 50 

In [ ]:
#### Ejemplo:

# Si A es:
# array([[59, 53, 45, 76],
#        [65, 43, 22, 88],
#        [29, 59,  8, 57],
#        [77, 85, 70, 48],
#        [29, 72, 35, 79],
#        [ 8, 99, 64, 76],
#        [53, 80, 50, 40],
#        [82, 99, 28, 22],
#        [10, 59, 13, 41],
#        [81, 75, 53, 75]]
#
# Y B es:
# array([14, 17, 75, 40, 86, 16, 77, 81, 77, 50]))

# Entonces se pide obtener:

#array([[29, 59,  8, 57],
#       [29, 72, 35, 79],
#       [53, 80, 50, 40],
#       [82, 99, 28, 22],
#       [10, 59, 13, 41]])


A = np.random.randint(100, size = (10,4))
B = np.random.randint(100, size = (10,))
B2 = B.reshape(10,1)



In [ ]:
print(A[(B2>50)[:,0]])
print(A[B>50])

[[23 59 61 53]
 [31 19 39 19]
 [60 14 26 66]
 [25 16 30 91]
 [28 84 67 93]
 [63 86 39  9]]
[[23 59 61 53]
 [31 19 39 19]
 [60 14 26 66]
 [25 16 30 91]
 [28 84 67 93]
 [63 86 39  9]]


#### Ejercicio 5

Definir una función `f_1_0(n)` que recibe un número natural n y devuelve un array bidimensional de n filas y n columnas que tiene 1s en los bordes y 0s en el interior.

In [ ]:
# Ejemplo:

# >>> f_1_0(10)

# array([[1., 1., 1., 1., 1., 1., 1., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 1., 1., 1., 1., 1., 1., 1.]])

def f_1_0(n):
    A[0, :] = 1
    A[-1, :] = 1
    A[:, 0] = 1
    A[:, -1] = 1
    return A

A = f_1_0(5)
print(A)


[[ 1  1  1  1]
 [ 1 59 61  1]
 [ 1 61 10  1]
 [ 1 47 32  1]
 [ 1 19 39  1]
 [ 1 14 26  1]
 [ 1 45 88  1]
 [ 1 16 30  1]
 [ 1 84 67  1]
 [ 1  1  1  1]]


#### Ejercicio 6

Generar un array unidimensional, con enteros de 20 a 32, y a continuación, usando indexado, invertir el orden. 

In [ ]:
# Ejemplo:

# A partir del array([32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20]), generar:
# array([32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20])





[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### Ejercicio 7

Definir una función g tal que dado un número natural n y otro entero k, obtiene un array bidimensional n x n con k (entero) en todas sus componentes 



In [ ]:
# Ejemplo:

# >>> g(5,9)

# array([[9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9]], dtype=int32)







#### Ejercicio 8

Crear una matriz bidimensional 8x8 con 1s y 0s como en un tablero de ajedrez.


In [ ]:
# Ejemplo:

# array([[1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)


M = np.zeros((8,8))
M[::2,::2] = 1
M[1::2, 1::2] = 1
print(M)





[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### Ejercicio 9

Generar una matriz 5x5 y normalizarla (restar la media y dividiendo por la desviación típica de todos los elementos). Hacerlo también normalizando cada columna por separado (restando la media y diviendo por la desviación típica de la columna en la que está el elemento).   

In [ ]:
# Ejemplo:

# Si A es:

# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24]])

# Entonces con la primera normalización quedaría:

# array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
#        [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
#        [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
#        [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
#        [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]]

# Y con la normalización por columnas:

M=np.arange(25).reshape(5,5)
(M-np.mean(M, axis=0))/np.std(M, axis=0)




array([[-1.41421356, -1.41421356, -1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356,  1.41421356]])

#### Ejercicio 10

Cambiar de signo todos los elementos de un array de enteros que estén entre 3 y 8.


In [ ]:
# Ejemplo:

# Si tenemos:

# array([[ 0,  1,  2, 3],
#        [ 4,  5,  6, 7],
#        [ 8,  9, 10, 11]])

# se trataría de obtener:

# array([[ 0,  1,  2, -3],
#        [-4, -5, -6, -7],
#        [-8, -9, 10, 11]])


M = np.arange(12).reshape(3,4)
np.where((M>=3)&(M<=8), -M, M)





array([[ 0,  1,  2, -3],
       [-4, -5, -6, -7],
       [-8,  9, 10, 11]])

In [ ]:
M[(M>=3)&(M<=8)]*=-1
M

array([[ 0,  1,  2, -3],
       [-4, -5, -6, -7],
       [-8,  9, 10, 11]])

#### Ejercicio 11

Dados dos arrays bidimensionales A y B del mismo tamaño, calcular `(A+B)*(-A/2)`, de manera que las operaciones se realicen sobre el espacio de memoria de A y B, sin generar copias.


In [ ]:
# Examen







#### Ejercicio 12

Supongamos que tenemos un array unidimensional con nombres de personas, y otro con sus respectivas edades. Usando *fancy indexing* y la función `np.argsort()`, obtener un array con los nombres ordenados de menor a mayor edad. 



In [ ]:
# --- Ejemplo:
nombres=np.array(["Juan","Luis","Ramón","Ana","Fernando","Beatriz","Carmen"])
edades=np.array([34,21,54,12,3,7,22])

# Ordenados según edad: array(['Fernando', 'Beatriz', 'Ana', 'Luis', 'Carmen', 'Juan', 'Ramón'],dtype='<U8')







#### Ejercicio 13 (Sección 4.7 del libro *Python for Data Analysis*, de W. McKinney)

Un *paseo aleatorio* es una sucesión de enteros, comenzando en 0, de manera que cada uno de ellos se obtiene sumando 1 o -1 al anterior, aleatoriamente y con igual probabilidad. 

Este es el código python para generar paseos aleatorios de 100 pasos:

In [ ]:
import random
posicion = 0
paseo = [posicion]
npasos = 100
for i in range(npasos):
    paso = 1 if random.randint(0, 1) else -1
    posicion += paso
    paseo.append(posicion)
    
print(paseo)

[0, -1, -2, -1, 0, -1, 0, -1, 0, -1, -2, -1, 0, -1, 0, 1, 2, 3, 2, 3, 2, 3, 4, 5, 6, 7, 6, 5, 6, 5, 4, 3, 2, 3, 2, 3, 2, 3, 4, 5, 4, 5, 4, 3, 4, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 15, 16, 17, 16, 17, 18, 17, 18, 19, 20, 19, 18, 19, 20, 21, 22, 21, 22, 23, 24, 25, 24, 23, 22, 23, 22, 23, 22, 23, 22, 21, 22, 23, 24, 25, 26, 27, 26, 27, 28, 29, 28]


**13.1** Definer una función `paseo_aleatorio(npasos)` que genere un paseo aleatorio de `npasos`, **usando numpy** . *Indicación:* usar `np.where` y `np.cumsum`.

In [ ]:
# Ejemplo:

# >>> paseo_aleatorio(100)
# array([ 1,  0, -1, -2, -3, -4, -5, -4, -3, -2, -1, -2, -1,  0, -1, -2, -1,
#        -2, -3, -4, -5, -4, -5, -6, -5, -4, -3, -2, -1,  0, -1,  0,  1,  2,
#         3,  2,  1,  2,  3,  4,  3,  2,  3,  4,  3,  2,  3,  2,  1,  2,  1,
#         2,  1,  0,  1,  2,  3,  4,  5,  4,  3,  2,  1,  0,  1,  0, -1,  0,
#        -1,  0,  1,  2,  1,  0, -1, -2, -1, -2, -3, -2, -1,  0, -1, -2, -1,
#        -2, -1,  0, -1, -2, -3, -2, -1,  0,  1,  2,  3,  4,  3,  2])








**13.2** Calcular la posición inferior y superior por la que pasa un paseo, y el momento en el que se alcanzan.

**13.3** Generar un paseo de 1000 pasos, y calcular:

* cuántas veces se está a más de 10 pasos de distancia del origen. 
* cuál es el primer paso en el que se separa a distancia 10 del origen.