# Herramientas python para ciencia de los datos

## Introducción a Numpy

Los ejemplos y la presentación que sigue está tomada del capítulo 4 del libro:

[*Python for Data Analysis*](https://wesmckinney.com/pages/book.html)  
**Wes McKinney**  
O'Reilly 2017

Github con el material del libro: [Github](https://github.com/wesm/pydata-book)

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

Numpy es quizás el paquete de computación numérica más impprtante de Python. Implementa arrays (matrices) multidimensionales de manera muy eficiente, con numerosas funcionalidades optimizadas sobre dicha estructura de datos. 

Es muy común en la comunidad python usar el alias `np` cundo importamos Numpy:

In [2]:
import numpy as np

Aunque en principio las listas de python podrían servir para representar array de varias dimensiones, la eficiencia de numpy es mucho mejor, al estar construido sobre una biblioteca de rutinas en lenguaje C. Además muchas de las operaciones numpy que actúan sobre todo el array, están optimizadas y permiten evitar los bucles `for`de python, que actúan más lentamente.

Lo que sigue es un ejemplo de un array de numpy unidimensional con un millón de componentes, y el análogo como lista python. 

In [3]:
arr1 = np.arange(1000000)
list1 = list(range(1000000))

Vamos a obtener el array resultante de multiplicar por 2 cada componente, y veamos el tiempo de CPU que se emplea. Nótese que en el caso de numpy, dicha operación se especifica simplemente como "multiplicar por 2" el array. En el caso de las listas, tenemos que usar un bucle `for` para la misma operación. Obsérvese la gran diferencia en el tiempo de ejecución:  

In [4]:
%time for _ in range(10): arr2 = arr1 * 2
%time for _ in range(10): list2 = [x * 2 for x in list1]

CPU times: user 6.41 ms, sys: 6.11 ms, total: 12.5 ms
Wall time: 11.4 ms
CPU times: user 180 ms, sys: 49.5 ms, total: 229 ms
Wall time: 236 ms


## Arrays de Numpy

La estructura de datos principal de numpy es el *array n-dimensional*. Como hemos dicho, numpy nos permite operar sobre los arrays en su totalidad,  especificando las operaciones como si lo hiciéramos con las componentes individuales. 

Lo que sigue genera un array de dos dimensiones, con dos filas y tres columnas, con numeros aleatorios (obtenidos como muestras de una distribución normal de media 0 y desviación típica 1).

In [5]:
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

Podemos por ejemplo obtener el array resultante de multiplicar cada componente del array por 10:

In [6]:
data * 10

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

O la suma de cada componente consigo mismo:

In [7]:
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

Nótese que las operaciones anteriores no cambian el array sobre el que operan:

In [8]:
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

Los arrays de numpy deben ser homogéneos, es decir todas sus componentes del mismo tipo. El tipo de los elementos de un array lo obtenemos con `dtype`: 

In [9]:
data.dtype

dtype('float64')

El método `ndim` nos da el número de dimensiones, y el método `shape` nos da el tamaño de cada dimensión, en forma de tupla. 

En este caso, tenemos que `data` es un array bidimensional, con 2 "filas" y 3 "columnas":

In [10]:
print(data.ndim)
print(data.shape)


2
(2, 3)


En la terminología de numpy, cada una de las dimensiones se denominan "ejes" (*axis*), y se numeran consecutivamente desde 0. Por ejemplo, en un array bidimensional, el eje 0 (*axis=0*) corresponde a las filas y el eje 1 corresponde a las columnas (*axis=1*). 

### Creación de arrays

La manera más fácil de crear arrays es mediante el método `np.array`. Basta con aplicarlo a cualquier dato python de tipo secuencia que sea susceptible de transformarse en un array. Por ejemplo, una lista de números se transforma en un array unidimensional: 

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Si le pasamos listas anidadas con una estructura correcta, podemos obtener el correspondiente array bidimensional: 

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Hay otras maneras de crear arrays. Damos a continuación solo algunos ejemplos:

In [13]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

Podemos usar también `reshape` para transformar entre distintas dimensiones. Por ejemplo, un uso típico es crear un array bidimensional a partir de uno unidimensional:

In [17]:
L=np.arange(12)
M=L.reshape(3,4) # también puedes poner  M=L.reshape(3,-1)
L,M

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

Hasta ahora sólo hemos visto ejemplos de arrays unidimensionales y bidimensionales. Estas son las dimensiones más frecuentes, pero numpy soporta arrays con cualquier número finito de dimensiones. Por ejemplo, aquí vemos un array de tres dimensiones:

In [18]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### Tipos de datos en las componentes de un array (*dtype*)

El tipo de dato de las componentes de un array está implícito cuando se crea, pero podemos especificarlo: 

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


Podemos incluso convertir el `dtype` de un array que ya se ha creado, usando el método `astype`. En el ejemplo que sigue, a partir de un array de enteros, obtenemos uno de números de coma flotante:

In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [21]:
float_arr = arr.astype(np.float64)
float_arr.dtype
float_arr

array([1., 2., 3., 4., 5.])

Podemos incluso pasar de coma flotante a enteros, en cuyo caso se trunca la parte decimal:

In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

O pasar de strings a punto flotante, siempre que los strings del array tengan sentido como números:

In [23]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Operaciones aritméticas con arrays

Una de las características más interesantes de numpy es la posibilidad de aplicar eficientes operaciones aritméticas "componente a componente" entre arrays, sin necesidad de usar bucles `for`. Basta con usar la correspondiente operación numérica de python. 

Veamos algunos ejemplos:

In [24]:
A = np.array([[1., 2., 3.], [4., 5., 6.]])
B = np.array([[8.1, -22, 12.3], [6.1, 7.8, 9.2]])

In [25]:
A * B

array([[  8.1, -44. ,  36.9],
       [ 24.4,  39. ,  55.2]])

In [26]:
A - B

array([[-7.1, 24. , -9.3],
       [-2.1, -2.8, -3.2]])

In [27]:
from collections import defaultdict
import math

def crea_estados(cuadricula):
        res = []
        for i in range(len(cuadricula)):
                for j in range(len(cuadricula[i])):    
                        if(cuadricula[i][j]!='x'):
                                res.append((i,j))
        return res
    
def matriz_pi_Robot(cuad):   
    estados = crea_estados(cuad)        
    tamaño = len(estados)
    proababilidad = 1/tamaño
    dic = defaultdict(int)
    for e in estados:
        dic[e]=proababilidad
    return dic 

def matriz_a_robot(cuad):
    estados = crea_estados(cuad)
    dic=defaultdict(float)
    for e1 in estados:
        listaVecinos=[]
        noVecinos = []
        for e2 in estados:
            if(cuad[e1[0]][e1[1]]=='E'): # Si la casilla es E
                if ((abs(e1[0]-e2[0])==1) and ((abs(e1[1]-e2[1])==1))): # Miro las diagonales disponibles
                    listaVecinos.append(e2) #añado las disponibles
                elif(((abs(e1[0]-e2[0])==1) and e2[1] == e1[1]) or 
                     ((abs(e1[1]-e2[1])==1) and e2[0] == e1[0])): # Miro las adyacentes disponibles
                    listaVecinos.append(e2) #añado las adyacentes disponibles
                else:
                    noVecinos.append(e2)    # Si no se cumple lo meto en no Vecino
            else:
                if (((abs(e1[0]-e2[0])==1) and e2[1] == e1[1]) or 
                     ((abs(e1[1]-e2[1])==1) and e2[0] == e1[0])): #Si es casilla o solo miro las adyacentes
                    listaVecinos.append(e2) #meto las adyacentes
                else:
                    noVecinos.append(e2)
        for e in listaVecinos:
            dic[(e1,e)]=1/len(listaVecinos)
        for e in noVecinos:
            dic[(e1,e)]=0      
    return dic         

def observables_robot():
    return [(0, 0, 0, 0),(0, 0, 0, 1),(0, 0, 1, 0),(0, 0, 1, 1),(0, 1, 0, 0),
    (0, 1, 0, 1),(0, 1, 1, 0),(0, 1, 1, 1),(1, 0, 0, 0),(1, 0, 0, 1),
    (1, 0, 1, 0),(1, 0, 1, 1),(1, 1, 0, 0),(1, 1, 0, 1),(1, 1, 1, 0),
    (1, 1, 1, 1)] 
    
def existe_estado(estado, estados):
    res = False
    for e in estados:
        if estado == e:
            res = True
    return res

def calcula_probabilidad(estado, obs, epsilon, estados):
    aciertos = 0
    fallos = 0
    #Norte libre
    if(existe_estado((estado[0] -1, estado[1]),estados)):
        if obs[0] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[0]==0):
            fallos += 1
        else:
            aciertos += 1
    #Sur libre
    if(existe_estado((estado[0] + 1, estado[1]),estados)):
        if obs[1] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[1]==0):
            fallos += 1
        else:
            aciertos += 1
    #Este libre
    if(existe_estado((estado[0], estado[1]+1),estados)):
        if obs[2] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[2]==0):
            fallos += 1
        else:
            aciertos += 1
    #Oeste libre
    if(existe_estado((estado[0], estado[1]-1), estados)):
        if obs[3] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[3]==0):
            fallos += 1
        else:
            aciertos += 1
    return (epsilon**(fallos)) * ((1-epsilon)**aciertos)
    

def matriz_b_robot(cuad,epsilon):
    dic = {}
    estados = crea_estados(cuad)
    for e in estados:
        for o in observables_robot():
            dic[(e,o)]=calcula_probabilidad(e,o,epsilon,estados)
    return dic
    
class HMM(object):
    """Clase para definir un modelo oculto de Markov"""

    def __init__(self,estados,mat_ini,mat_trans,observables,mat_obs):
        """El constructor de la clase recibe una lista con los estados, otra
        lista con los observables, un diccionario representado la matriz de
        probabilidades de transición, otro diccionario con la matriz de
        probabilidades de observación, y otro con las probabilidades de
        inicio. Supondremos (no lo comprobamos) que las matrices son 
        coherentes respecto de la  lista de estados y de observables."""
        
        self.estados=estados
        self.observables=observables
        self.a={(si,sj):ptrans
                for (si,l) in zip(estados,mat_trans)
                for (sj,ptrans) in zip(estados,l)}
        self.b={(si,vj):pobs
                for (si,l) in zip(estados,mat_obs)
                for (vj,pobs) in zip(observables,l)}
        self.pi=dict(zip(estados,mat_ini))


ej1_hmm=HMM(["c","f"],
            [0.8,0.2],
            [[0.7,0.3],[0.4,0.6]],
            [1,2,3],   
            [[0.2,0.4,0.4],[0.5,0.4,0.1]])
            

ej2_hmm=HMM(["l","no l"],
            [0.5,0.5],
            [[0.7, 0.3], [0.3,0.7]],
            ["u","no u"],   
            [[0.9,0.1],[0.2,0.8]])

class Robot(HMM):
    def __init__(self, cuadricula, epsilon):
        self.cuadricula = cuadricula
        self.epsilon = epsilon
        self.estados = crea_estados(cuadricula)
        self.pi = matriz_pi_Robot(cuadricula)
        self.a = matriz_a_robot(cuadricula)
        self.observables = observables_robot()
        self.b = matriz_b_robot(cuadricula, epsilon)

In [28]:
import math
 
    


In [29]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==========================================================
# Ampliación de Inteligencia Artificial. Tercer curso.
# Grado en Ingeniería Informática - Tecnologías Informáticas
# Curso 2023-24
# Primer entregable
# ===========================================================

# -----------------------------------------------------------
# NOMBRE: Adrián 
# APELLIDOS: González Lillo
# -----------------------------------------------------------



# Escribir el código Python de las funciones que se piden en el
# espacio que se indica en cada ejercicio.

# IMPORTANTE: NO CAMBIAR EL NOMBRE NI A ESTE ARCHIVO NI A LAS FUNCIONES QUE SE
# PIDEN (aquellas funciones con un nombre distinto al que se pide en el
# ejercicio NO se corregirán).

# ESTE ENTREGABLE SUPONE 1 PUNTO DE LA NOTA TOTAL

# *****************************************************************************
# HONESTIDAD ACADÉMICA Y COPIAS: la realización de los ejercicios es un
# trabajo personal, por lo que deben completarse por cada estudiante de manera
# individual.  La discusión con los compañeros y el intercambio de información
# DE CARÁCTER GENERAL con los compañeros se permite, pero NO AL NIVEL DE
# CÓDIGO. Igualmente el remitir código de terceros, obtenido a través
# de la red, mediante herramientas de genración de código, o cualquier otro medio
# SE CONSIDERARÁ PLAGIO.

# Cualquier plagio o compartición de código que se detecte significará
# automáticamente la calificación de CERO EN LA ASIGNATURA para TODOS los
# estudiantes involucrados, independientemente de otras medidas de carácter
# DISCIPLINARIO que se pudieran tomar. Por tanto a estos estudiantes NO se les
# conservará, para futuras convocatorias, ninguna nota que hubiesen obtenido
# hasta el momento.
# *****************************************************************************



# Lo que sigue es la implementación de la clase HMM vista en la práctica de clase,
# que representa de manera genérica un modelo oculto de Markov, junto con los
# dos ejemplos de las diapositivas.

class HMM(object):
    """Clase para definir un modelo oculto de Markov"""

    def __init__(self,estados,mat_ini,mat_trans,observables,mat_obs):
        """El constructor de la clase recibe una lista con los estados, otra
        lista con los observables, un diccionario representado la matriz de
        probabilidades de transición, otro diccionario con la matriz de
        probabilidades de observación, y otro con las probabilidades de
        inicio. Supondremos (no lo comprobamos) que las matrices son 
        coherentes respecto de la  lista de estados y de observables."""
        
        self.estados=estados
        self.observables=observables
        self.a={(si,sj):ptrans
                for (si,l) in zip(estados,mat_trans)
                for (sj,ptrans) in zip(estados,l)}
        self.b={(si,vj):pobs
                for (si,l) in zip(estados,mat_obs)
                for (vj,pobs) in zip(observables,l)}
        self.pi=dict(zip(estados,mat_ini))


ej1_hmm=HMM(["c","f"],
            [0.8,0.2],
            [[0.7,0.3],[0.4,0.6]],
            [1,2,3],   
            [[0.2,0.4,0.4],[0.5,0.4,0.1]])
            

ej2_hmm=HMM(["l","no l"],
            [0.5,0.5],
            [[0.7, 0.3], [0.3,0.7]],
            ["u","no u"],   
            [[0.9,0.1],[0.2,0.8]])


# Lo que sigue son implementaciones de los algoritmos de avance y de viterbi:

def avance(hmm,observaciones):
    """Algoritmo de avance (forward). Dada una secuencia de observaciones
    hasta el instante t, devuelve la probabilidad de cada estado 
    en el instante t y la probabilidad de la secuencia de observaciones"""
    
    alpha_list=[hmm.b[(e,observaciones[0])]*hmm.pi[e] 
                for e in hmm.estados]
    for o in observaciones[1:]:
        alpha_list=[hmm.b[(e,o)]*sum(hmm.a[(e1,e)]*a 
                                       for (e1,a) in zip(hmm.estados,alpha_list)) 
                    for e in hmm.estados]
        
    prob_secuencia=sum(alpha_list)
    alpha_list_n=[(p/prob_secuencia) for p in alpha_list] 
    return dict(zip(hmm.estados,alpha_list_n)) 


def viterbi(hmm,observaciones):
        """Algoritmo de Viterbi. Dada una secuancia de observaciones, devuelve
        la secuencia de estados más probable"""

        def max_argmax(l):
            """Si l es una lista numérica, devuelve el índice del valor máximo
            y ese valor"""
            return max(enumerate(l),key=lambda x:x[1])

        def mult_seg(x,p):
            """Multiplica por x la segunda componente de un par p"""
            return (p[0],x*p[1])

        pr_nu_list=[(None,hmm.b[(e,observaciones[0])]*hmm.pi[e]) 
                              for e in hmm.estados]
        historia=dict()
        for (i,o) in enumerate(observaciones[1:]):

            historia[i]=pr_nu_list
            pr_nu_list=[mult_seg(hmm.b[(e,o)],max_argmax(hmm.a[(e1,e)]*alpha 
                                                for (e1,(_,alpha)) in zip(hmm.estados,pr_nu_list)))
                                            for e in hmm.estados]
        (m,(ptr,_))=max(enumerate(pr_nu_list),key=lambda x:x[1][1])
        secuencia=[hmm.estados[m]]
        for k in range(len(observaciones)-2,-1,-1):
            secuencia.append(hmm.estados[ptr])
            (ptr,_)=historia[k][ptr]
        return list(reversed(secuencia))    




# Un algoritmo de muestreo de secuencias de estados y observaciones en HMMs, 
# también visto en la práctica realizada en clase:
        

from collections import defaultdict
import random

def muestreo_hmm(hmm,n):
    """Genera una secuencia de estados junto con su correspondiente
    secuencia de observaciones, de longitud n"""

    def muestreo_ini():
        """Devuelve aleatoriamente (siguiendo las probabilidades del
        modelo) el primer estado en la secuencia"""

        aleatorio=random.random()
        acum=0
        for x in hmm.estados:
            acum+=hmm.pi[x]
            if acum > aleatorio:
                return x
            
    def muestreo_cond(estado,lista,mat_prob):
        """Esta función se usa para dos tareas muy similares:
           - Dado el estado actual, devolver aleatoriamente (pero
             siguiendo las probabilidades del modelo), el estado sigueinte
             en la secuencia. En ese caso, lista es la lista de estados y
             mat_prob la matriz de probabilidades de transición. 

           - Dado el estado actual, devolver aleatoriamento (pero
             siguiendo las probabilidades del modelo), la observación
             correspondiente a ese estado. En ese caso, lista es la lista
             de observables y mat_prob es la matriz de probabilidades de
             observación."""

        aleatorio=random.random()
        acum=0
        for x in lista:
            acum+=mat_prob[estado,x]
            if acum > aleatorio:
                return x

            
    secuencia_estados=[muestreo_ini()]
    secuencia_obs=[muestreo_cond(secuencia_estados[-1],hmm.observables,hmm.b)]

    for _ in range(n-1):
        secuencia_estados.append(muestreo_cond(secuencia_estados[-1],hmm.estados,hmm.a)) 
        secuencia_obs.append(muestreo_cond(secuencia_estados[-1],hmm.observables,hmm.b))

    return secuencia_estados, secuencia_obs



# Y una función que realiza una estimación de  P(X_t| o1,o2,...,o_n), 
# usando la función de muestreo anterior. 





# ===============================================================
# Parte 1: Probabilidad de filtrado usando muestreos ponderados
#=====================================================================


# Modificar las dos funciones anteriores para realizar la estimación de
# P(X_t| o1,o2,...,o_n), usando muestreo con ponderación por verosimilitud.  
# 
# Es decir, se trata de definir:
    
# * Una función muestreo_hmm_por_verosimilitud(hmm, obs) que recibe un modelo 
#   oculto de Markov hmm y una secuencia de observaciones obs, y genera una
#   secuencia de estados mediante muestreo, dando por supuesto que la secuencia de 
#   observaciones correspondiente es la dada por obs. Además de esa  secuencia 
#   de estados, devuelve una ponderación de la muestra generada. Esa ponderación
#   se obtiene multiplicando las probabilidades de que cada observación de la 
#   secuencia dada hubiera ocurrido si se hubiese muestreado. 


# * Una función estima_filtrado_por_verosimilitud(hmm,obs,n_muestras) que 
#   que recibiendo un modelo oculto de Markov hmm, una secuencia de observaciones
#   y un entero n_muestras indicando el número de muestras a generar, haga una
#   estimación de las probabilidades de cada estado dado que se ha observado la 
#   secuencia de observaciones dada, usando para ello la función de 
#   muestreo_hmm_por_verosimilitud anterior.

# Ejemplos (no necesariamente debe salir lo mismo):
    
# >>> muestreo_hmm_por_verosimilitud(ej1_hmm,[2, 1, 1, 1, 3])
# (['c', 'c', 'c', 'c', 'c'], 0.00128)    

# >>> muestreo_hmm_por_verosimilitud(ej2_hmm,['u', 'no u', 'u'])
# (['l', 'l', 'l'], 0.081)


# >>> estima_filtrado_por_verosimilitud(ej1_hmm,[3,1,3,2],100000)
# {'c': 0.6477223509962132, 'f': 0.35227764900378683}

# >>> estima_filtrado_por_verosimilitud(ej2_hmm,["u","u","no u"],100000)
# {'l': 0.19304969498121577, 'no l': 0.8069503050187843}
   
def muestreo_hmm_por_verosimilitud(hmm,obs):
    """Genera una secuencia de estados junto con su correspondiente
    secuencia de observaciones, de longitud n"""

    def muestreo_ini():
        """Devuelve aleatoriamente (siguiendo las probabilidades del
        modelo) el primer estado en la secuencia"""

        aleatorio=random.random()
        acum=0
        for x in hmm.estados:
            acum+=hmm.pi[x]
            if acum > aleatorio:
                return x
            
    def muestreo_cond(estado,lista,mat_prob):
        """Esta función se usa para dos tareas muy similares:
           - Dado el estado actual, devolver aleatoriamente (pero
             siguiendo las probabilidades del modelo), el estado sigueinte
             en la secuencia. En ese caso, lista es la lista de estados y
             mat_prob la matriz de probabilidades de transición. 

           - Dado el estado actual, devolver aleatoriamento (pero
             siguiendo las probabilidades del modelo), la observación
             correspondiente a ese estado. En ese caso, lista es la lista
             de observables y mat_prob es la matriz de probabilidades de
             observación."""

        aleatorio=random.random()
        res=0
        for x in lista:
            res+=mat_prob[estado,x]
            if res > aleatorio:
                return x
            
    secuencia_estados=[muestreo_ini()]

    for _ in range(len(obs)-1):
        secuencia_estados.append(muestreo_cond(secuencia_estados[-1],hmm.estados,hmm.a)) 

    res = 1
    for z1,z2 in zip(secuencia_estados, obs):
        res = res * hmm.b[(z1,z2)] 

    return secuencia_estados, res


def estima_filtrado_por_verosimilitud(hmm,obs,n_muestras):      
        ocurrencias_estados={e:0 for e in hmm.estados}
        for _ in range(n_muestras):
            secuencia_est,dato=muestreo_hmm_por_verosimilitud(hmm,obs)
            ocurrencias_estados[secuencia_est[-1]]+= dato
        norm = sum(ocurrencias_estados.values())
        return {e:m_e/norm for e,m_e in ocurrencias_estados.items()}


#=====================================================================
# Parte 2: Aplicación al movimiento de robots
#=====================================================================

# Vamos ahora a aplicar el algoritmo de viterbi para experimentar sobre
# un problema simple de localización de robots que se mueve en una cuadrícula.
# Esta aplicación es similar (aunque no igual) a la  descrita en la sección 
# 14.3.2 del libro "Artificial Intelligence: A Modern Approach (4th edition)" 
# de S. Russell y P. Norvig.

# Supongamos que tenemos la siguiente lista de strings, que representa una
# cuadrícula bidimensional, sobre la que se desplaza un robot:

#     ["ooooxoooooxoooxo",
#      "xxooxoxxoxoxExxo",
#      "xoEoxoxxoooooxxo",
#      "ooxooExooooxoooo"]

# Aquí la "x" representa una casilla bloquedada, y la "o" representa una
# casilla libre en la que puede estar el robot. La "E" representa también casilla 
# libre, pero con un tratamiento especial que más adelante se detalla. 

#   El robot puede iniciar su movimiento en cualquiera de las casillas libres,
# con igual probabilidad. En cada instante, si está en una casilla marcada 
# con "o", el robot se mueve a una casilla contigua no oblicua: al norte, al sur, 
# al este o al oeste, siempre que dicha casilla no esté bloqueda. Si la casilla en la 
# que se encuentra está marcada con "E", entonces además de poderse mover al 
# norte, sur, este y oeste, puede moverse a una casilla en oblicuo (NE,NO,SE,SO), 
# entendiendo siempre que la casilla a la que se mueva no puede estar bloqueada.     

# El movimiento del robot está sujeto a incertidumbre (no está determinada a qué 
# vecina se moverá), pero sabemos que se puede mover CON IGUAL PROBABILIDAD A CADA
# CASILLA VECINA NO BLOQUEADA, teniendo en cuenta que la noción de vecina accesible
# difiere si se trata de una casilla especial.     

#   Desgraciadamente, el robot no nos comunica en qué casilla se encuentra en
# cada instante de tiempo, ni nosotros podemos observarlo. Lo único que el
# robot puede observar en cada casilla son las direcciones hacia las que
# existen obstáculos (es decir, casillas bloqueadas o paredes). Por ejemplo, una
# observación "N-S" representa que el robot ha detectado que desde la casilla
# en la que está, al norte y al sur no pueda transitar, pero que sí puede
# hacerlo a las casillas que están al este y al oeste. Tanto en las casillas normales
# como en las especiales, los sensores solo detectan posibles bloqueos al N, S, E y O 
# (es decir, el sensor nunca detecta en oblicuo, tampoco en las casillas especiales)    

#   Para acabar de complicar la cosa, los sensores de obstáculos que tiene el
# robot no son perfectos, y están sujetos a una probabilidad de error.
# Supondremos que hay una probabilidad epsilon de que la detección de
# obstáculo en una dirección sea errónea (y por tanto, hay una probabilidad
# 1-epsilon de que sea correcta). Supondremos también que los errores en
# cada una de las cuatro direcciones son independientes entre sí. Esto nos
# permite calcular la probabilidad de las observaciones dados los estados, como
# ilustramos a continuación.

#   Por ejemplo, supongamos que X y E son, respectivamente, las variables
# aleatorias que indican la casilla en la que está el robot y la observación
# que realiza el robot. Supongamos también que c es una casilla que hacia el
# norte y el este tiene obstáculos, y que tiene casillas transitables al sur y
# al oeste. Si por ejemplo el robot informara que existen obstáculos al sur y
# al este, la probabilidad de esto sería 

#     P(E="S-E"|X=c) = (epsilon)^2 * (1-epsilon)^2 

# (ya que habría errado en dos direcciones, norte y sur, y acertado en otras
# dos, este y oeste). 

# Por el contrario, la probabilidad de que en ese mismo estado el robot
# informara de obstáculos al norte, sur y este, sería 

#     P(E="N-S-E"|X=c) = epsilon * (1-epsilon)^3 

# (ya que habría errado en una dirección y acertado en tres).

#robot0.b
#{((0, 0), (0, 0, 0, 0)): 0.008100000000000001,
# ((0, 0), (0, 0, 0, 1)): 0.07290000000000002,
# ((0, 0), (0, 0, 1, 0)): 0.0009000000000000002,
# ((0, 0), (0, 0, 1, 1)): 0.008100000000000001,

# Se pide:

# Definir una clase Robot, subclase de HMM, cuyo constructor reciba una lista
# de strings del estilo de la del ejemplo anterior, y un error epsilon, generando a
# partir de la misma un objeto de la clase HMM. Importante: se pide hacerlo de 
# manera genérica, no solo para la cuadrícula del ejemplo. 

# Aplicar el algoritmo de Viterbi a varias secuencias de observaciones del robot,
# para estimar las correspondientes secuencias de casillas más probables por
# las que ha pasado el robot, en la cuadrícula del ejemplo.

from collections import defaultdict
import math

def crea_estados(cuadricula):
        res = []
        for i in range(len(cuadricula)):
                for j in range(len(cuadricula[i])):    
                        if(cuadricula[i][j]!='x'):
                                res.append((i,j))
        return res
    
def matriz_pi_Robot(cuad):   
    estados = crea_estados(cuad)        
    tamaño = len(estados)
    proababilidad = 1/tamaño
    dic = defaultdict(int)
    for e in estados:
        dic[e]=proababilidad
    return dic 

def matriz_a_robot(cuad):
    estados = crea_estados(cuad)
    dic=defaultdict(float)
    for e1 in estados:
        listaVecinos=[]
        noVecinos = []
        for e2 in estados:
            if(cuad[e1[0]][e1[1]]=='E'): # Si la casilla es E
                if ((abs(e1[0]-e2[0])==1) and ((abs(e1[1]-e2[1])==1))): # Miro las diagonales disponibles
                    listaVecinos.append(e2) #añado las disponibles
                elif(((abs(e1[0]-e2[0])==1) and e2[1] == e1[1]) or 
                     ((abs(e1[1]-e2[1])==1) and e2[0] == e1[0])): # Miro las adyacentes disponibles
                    listaVecinos.append(e2) #añado las adyacentes disponibles
                else:
                    noVecinos.append(e2)    # Si no se cumple lo meto en no Vecino
            else:
                if (((abs(e1[0]-e2[0])==1) and e2[1] == e1[1]) or 
                     ((abs(e1[1]-e2[1])==1) and e2[0] == e1[0])): #Si es casilla o solo miro las adyacentes
                    listaVecinos.append(e2) #meto las adyacentes
                else:
                    noVecinos.append(e2)
        for e in listaVecinos:
            dic[(e1,e)]=1/len(listaVecinos)
        for e in noVecinos:
            dic[(e1,e)]=0      
    return dic         

def observables_robot():
    return [(0, 0, 0, 0),(0, 0, 0, 1),(0, 0, 1, 0),(0, 0, 1, 1),(0, 1, 0, 0),
    (0, 1, 0, 1),(0, 1, 1, 0),(0, 1, 1, 1),(1, 0, 0, 0),(1, 0, 0, 1),
    (1, 0, 1, 0),(1, 0, 1, 1),(1, 1, 0, 0),(1, 1, 0, 1),(1, 1, 1, 0),
    (1, 1, 1, 1)] 
    
def existe_estado(estado, estados):
    res = False
    for e in estados:
        if estado == e:
            res = True
    return res

def calcula_probabilidad(estado, obs, epsilon, estados):
    aciertos = 0
    fallos = 0
    #Norte libre
    if(existe_estado((estado[0] -1, estado[1]),estados)):
        if obs[0] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[0]==0):
            fallos += 1
        else:
            aciertos += 1
    #Sur libre
    if(existe_estado((estado[0] + 1, estado[1]),estados)):
        if obs[1] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[1]==0):
            fallos += 1
        else:
            aciertos += 1
    #Este libre
    if(existe_estado((estado[0], estado[1]+1),estados)):
        if obs[2] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[2]==0):
            fallos += 1
        else:
            aciertos += 1
    #Oeste libre
    if(existe_estado((estado[0], estado[1]-1), estados)):
        if obs[3] == 0:
            aciertos += 1
        else:
            fallos += 1
    else:
        if(obs[3]==0):
            fallos += 1
        else:
            aciertos += 1
    return (epsilon**(fallos)) * ((1-epsilon)**aciertos)
    

def matriz_b_robot(cuad,epsilon):
    dic = {}
    estados = crea_estados(cuad)
    for e in estados:
        for o in observables_robot():
            dic[(e,o)]=calcula_probabilidad(e,o,epsilon,estados)
    return dic
    
class HMM(object):
    """Clase para definir un modelo oculto de Markov"""

    def __init__(self,estados,mat_ini,mat_trans,observables,mat_obs):
        """El constructor de la clase recibe una lista con los estados, otra
        lista con los observables, un diccionario representado la matriz de
        probabilidades de transición, otro diccionario con la matriz de
        probabilidades de observación, y otro con las probabilidades de
        inicio. Supondremos (no lo comprobamos) que las matrices son 
        coherentes respecto de la  lista de estados y de observables."""
        
        self.estados=estados
        self.observables=observables
        self.a={(si,sj):ptrans
                for (si,l) in zip(estados,mat_trans)
                for (sj,ptrans) in zip(estados,l)}
        self.b={(si,vj):pobs
                for (si,l) in zip(estados,mat_obs)
                for (vj,pobs) in zip(observables,l)}
        self.pi=dict(zip(estados,mat_ini))


ej1_hmm=HMM(["c","f"],
            [0.8,0.2],
            [[0.7,0.3],[0.4,0.6]],
            [1,2,3],   
            [[0.2,0.4,0.4],[0.5,0.4,0.1]])
            

ej2_hmm=HMM(["l","no l"],
            [0.5,0.5],
            [[0.7, 0.3], [0.3,0.7]],
            ["u","no u"],   
            [[0.9,0.1],[0.2,0.8]])

class Robot(HMM):
    def __init__(self, cuadricula, epsilon):
        self.cuadricula = cuadricula
        self.epsilon = epsilon
        self.estados = crea_estados(cuadricula)
        self.pi = matriz_pi_Robot(cuadricula)
        self.a = matriz_a_robot(cuadricula)
        self.observables = observables_robot()
        self.b = matriz_b_robot(cuadricula, epsilon)




# NOTAS: 

# - Representar los estados por pares de coordenadas, en el que la (0,0) sería
#   la casilla de arriba a la izquierda. 
# - Nótese que en total son 16 posibles observaciones. Las observaciones las 
#   representamos por una tupla (i1,i2,i3,i4), en el que  sus elementos son 
#   0 ó 1, donde 0 indica que no se ha detectado obstáculo, y 1, indica que sí, 
#   respectivamente en  el N,S, E y O (en ese orden). 
#   Por ejemplo (1,1,0,0) indica que se detecta obstáculo en el N y en el S.
#   y (0,0,1,0) indica que se detecta obstáculo solo en el E.  
# - Supondremos que NO hay casillas bloqueadas (es decir, sin vecinos).    



# Ejemplo de HMM generado para una cuadrícula básica:
    
cuadr0=["ooo",
        "oxE",
        "ooo"]

# >>> robot0=Robot(cuadr0,0.1)

# >>> robot0.estados
# [(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]

# >>> robot0.observables

#[(0, 0, 0, 0),(0, 0, 0, 1),(0, 0, 1, 0),(0, 0, 1, 1),(0, 1, 0, 0),
# (0, 1, 0, 1),(0, 1, 1, 0),(0, 1, 1, 1),(1, 0, 0, 0),(1, 0, 0, 1),
# (1, 0, 1, 0),(1, 0, 1, 1),(1, 1, 0, 0),(1, 1, 0, 1),(1, 1, 1, 0),
# (1, 1, 1, 1)]

# >>> robot0.pi 
# {(0, 0): 0.125, (0, 1): 0.125, (0, 2): 0.125, (1, 0): 0.125,
#  (1, 2): 0.125, (2, 0): 0.125, (2, 1): 0.125, (2, 2): 0.125}

# >>> robot0.a
 
#{((0, 0), (0, 0)): 0, ((0, 0), (0, 1)): 0.5, ((0, 0), (0, 2)): 0,
# ((0, 0), (1, 0)): 0.5,((0, 0), (1, 2)): 0, ((0, 0), (2, 0)): 0,
# ((0, 0), (2, 1)): 0, ((0, 0), (2, 2)): 0,
# ((0, 1), (0, 0)): 0.5, ((0, 1), (0, 1)): 0, ((0, 1), (0, 2)): 0.5,
# ((0, 1), (1, 0)): 0, ((0, 1), (1, 2)): 0, ((0, 1), (2, 0)): 0,
# ((0, 1), (2, 1)): 0, ((0, 1), (2, 2)): 0,
# ((0, 2), (0, 0)): 0, ((0, 2), (0, 1)): 0.5,
# ...
#  ((1, 2), (0, 0)): 0, ((1, 2), (0, 1)): 0.25, # (1,2) es la casilla especial
# ((1, 2), (0, 2)): 0.25, ((1, 2), (1, 0)): 0,
# ((1, 2), (1, 2)): 0, ((1, 2), (2, 0)): 0,
# ((1, 2), (2, 1)): 0.25, ((1, 2), (2, 2)): 0.25,
# ....
# ... Continúa .....

# >>> robot0.b
#{((0, 0), (0, 0, 0, 0)): 0.008100000000000001,
# ((0, 0), (0, 0, 0, 1)): 0.07290000000000002,
# ((0, 0), (0, 0, 1, 0)): 0.0009000000000000002,
# ((0, 0), (0, 0, 1, 1)): 0.008100000000000001,
#  ... Continúa ....



# -----------

# Ejemplo de uso de Viterbi en la cuadrícula del ejemplo




cuadr_ej=     ["ooooxoooooxoooxo",
                "xxooxoxxoxoxExxo",
                "xoEoxoxxoooooxxo",
                "ooxooExooooxoooo"]




robot_ej_hmm=Robot(cuadr_ej,0.15)

# Secuencia de 7 observaciones:
seq_ej1=[(1, 1, 0, 0), (0, 1, 0, 0), (0, 1, 0, 1), (0, 1, 0, 1),
        (1, 1, 0, 0),(0, 1, 1, 0),(1, 1, 0, 0)]

# Usando Viterbi, estimamos las casillas por las que ha pasado:

viterbi(robot_ej_hmm,seq_ej1)
# [(3, 14), (3, 13), (3, 12), (3, 13), (3, 14), (3, 15), (3, 14)]















#=====================================================================
# Parte 3: Experimentaciones
#=====================================================================


# Realizar experimentos para ver cómo de buenas son las secuencias que se
# obtienen con el algoritmo de Viterbi que se ha implementado. Para ello, una
# manera podría ser la siguiente: generar una secuencia de estados y la
# correspondiente secuencia de observaciones usando el algoritmo de
# muestreo. La secuencia de observaciones obtenida se puede usar como entrada
# al algoritmo de Viterbi y comparar la secuencia obtenida con la secuencia de
# estados real que ha generado las observaciones. Se pide ejecutar con varios
# ejemplos y comprobar cómo de ajustados son los resultados obtenidos. Para
# medir el grado de coincidencia entre las dos secuencias de estados, calcular
# la proporción de estados coincidentes, respecto del total de estados de la
# secuencia.


# Por ejemplo:

# Función que calcula el porcentaje de coincidencias:
def compara_secuencias(seq1,seq2):
    return sum(x==y for x,y in zip(seq1,seq2))/len(seq1)


# Generamos una secuencia de 20 estados y observaciones
# >>> seq_e,seq_o=muestreo_hmm(robot_ej_hmm,20)

# >>> seq_o 
# [(0, 0, 1, 1), (0, 1, 1, 0), (1, 1, 0, 0),....]

# >>> seq_e
# [(2, 5),(3, 5), (3, 4), (3, 3), (3, 4), ....]
 
# >>> seq_estimada=viterbi(robot_ej_hmm,seq_o)

# >>> seq_estimada
# [(2, 5),(3, 5),(3, 4),(3, 3),(3, 4),(3, 5),...]
 
# Vemos, cuántas coincidencias hay, proporcinalmente al total de estados de la 
# secuencia:
    
# >>> compara_secuencias(seq_e,seq_estimada)
# 0.95

# -----------------------------------

# Para mecanizar esta experimentación, definir una función

#     experimento_hmm_robot_viterbi(cuadricula,epsilon,n,m) 

def experimento_hmm_robot_viterbi(cuadricula,epsilon,n,m):
    lista = []
    rob = Robot(cuadricula, epsilon)
    for _ in range(m):
        seq_e,seq_o=muestreo_hmm(rob,n)
        seq_estimada=viterbi(rob,seq_o)
        b = compara_secuencias(seq_e,seq_estimada)
        lista.append(b)
    return sum(lista)/len(lista)
        

# que genera el HMM correspondiente a la cuadrícula y al epsilon, y realiza 
# m experimentos, como se ha descrito:
    
# - generar en cada uno de ellos una secuencia de n observaciones y estados 
#  (con muestreo_hmm)
# - con la secuencia de observaciones, llamar a viterbi para estimar la 
#   secuencia de estados más probable
# - calcular qué proporción de coincidencias hay entre la secuencia de estados real 
#   y la que ha estimado viterbi 
# Y devuelve la media de los m experimentos. 

# Experimentar al menos con la cuadrícula del ejemplo y con varios valores de
# n, con varios valores de epsilon y con un m suficientemente grande para que 
# la media devuelta sea significativa del rendimiento del algoritmo. 






In [30]:
Robot1=Robot(cuadr0, 0.1)
calcula_probabilidad((0,0), (0,0,0,0), 0.1, crea_estados(cuadr0))

0.008100000000000001

In [31]:
cuadr_ej=     ["ooooxoooooxoooxo",
                "xxooxoxxoxoxExxo",
                "xoEoxoxxoooooxxo",
                "ooxooExooooxoooo"]
robot_ej_hmm=Robot(cuadr_ej,0.15)
seq_ej1=[(1, 1, 0, 0), (0, 1, 0, 0), (0, 1, 0, 1), (0, 1, 0, 1), (1, 1, 0, 0),(0, 1, 1, 0),(1, 1, 0, 0)]
viterbi(robot_ej_hmm,seq_ej1)

[(3, 4), (3, 3), (3, 4), (3, 3), (3, 4), (3, 5), (3, 4)]

In [32]:
Robot1.b


{((0, 0), (0, 0, 0, 0)): 0.008100000000000001,
 ((0, 0), (0, 0, 0, 1)): 0.0729,
 ((0, 0), (0, 0, 1, 0)): 0.0009000000000000002,
 ((0, 0), (0, 0, 1, 1)): 0.008100000000000001,
 ((0, 0), (0, 1, 0, 0)): 0.0009000000000000002,
 ((0, 0), (0, 1, 0, 1)): 0.008100000000000001,
 ((0, 0), (0, 1, 1, 0)): 0.00010000000000000002,
 ((0, 0), (0, 1, 1, 1)): 0.0009000000000000002,
 ((0, 0), (1, 0, 0, 0)): 0.0729,
 ((0, 0), (1, 0, 0, 1)): 0.6561,
 ((0, 0), (1, 0, 1, 0)): 0.008100000000000001,
 ((0, 0), (1, 0, 1, 1)): 0.0729,
 ((0, 0), (1, 1, 0, 0)): 0.008100000000000001,
 ((0, 0), (1, 1, 0, 1)): 0.0729,
 ((0, 0), (1, 1, 1, 0)): 0.0009000000000000002,
 ((0, 0), (1, 1, 1, 1)): 0.008100000000000001,
 ((0, 1), (0, 0, 0, 0)): 0.008100000000000001,
 ((0, 1), (0, 0, 0, 1)): 0.0009000000000000002,
 ((0, 1), (0, 0, 1, 0)): 0.0009000000000000002,
 ((0, 1), (0, 0, 1, 1)): 0.00010000000000000002,
 ((0, 1), (0, 1, 0, 0)): 0.0729,
 ((0, 1), (0, 1, 0, 1)): 0.008100000000000001,
 ((0, 1), (0, 1, 1, 0)): 0.0081000000000

En principio, para poder aplicar estas operaciones entre arrays, se deben aplicar sobre arrays con las mismas dimensiones (el mismo `shape`). Es posible operar entre arrays de distintas dimensiones, con el mecanismo de *broadcasting*, pero es ésta una característica avanzada de numpy que no veremos aquí.  

Podemos efectuar operaciones entre arrays y números (*escalares*), indicando con ello que la operación con el escalar se aplica a cada uno de los componentes del array. Vemos algunos ejemplos: 

In [33]:
3+B

array([[ 11.1, -19. ,  15.3],
       [  9.1,  10.8,  12.2]])

In [34]:
1 / A

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [35]:
A ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

Igualmente, podemos efectuar comparaciones aritméticas entre dos arrays, obteniendo el correspondiente array de booleanos como resultado:

In [36]:
A > B-5

array([[False,  True, False],
       [ True,  True,  True]])

En todos los casos anteriores, nótese que estas operaciones no modifican los arrays sobre los que se aplican, sino que obtienen un nuevo array con el correspondiente resultado.

### Indexado y *slicing* (operaciones básicas) 

Otra de las características más interesantes de numpy es la gran flexibilidad para acceder a las componentes de un array, o a un subconjunto del mismo. Vamos a ver a continuación algunos ejemplos básicos.

**Arrays unidimensonales**

Para arrays unidimensionales, el acceso es muy parecido al de listas. Por ejemplo, acceso a las componentes:

In [37]:
C = np.arange(10)*2
C

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
C[5]

10

La operación de *slicing* en arrays es similar a la de listas. Por ejemplo:

In [39]:
C[5:8]

array([10, 12, 14])

Sin embargo, hay una diferencia fundamental: en general en python, el slicing siempre crea *una copia* de la secuencia original. En numpy, el *slicing* es una *vista* de array original. Esto tiene como consecuencia que las modificaciones que se realicen sobre dicha vista se están realizando sobre el array original. Por ejemplo:   

In [40]:
C[5:8] = 12
C

array([ 0,  2,  4,  6,  8, 12, 12, 12, 16, 18])

Y además hay que tener en cuenta que cualquier referencia a una vista es en realidad una referencia a los datos originales, y que las modificaciones que se realicen a través de esa referencia, se realizarán igualmente sobre el original.

Veámos esto con el siguiente ejemplo:

In [41]:
# C_slice referencia a las componenentes 5, 6 y 7 del array C.
C_slice = C[5:8]
C_slice

array([12, 12, 12])

Modificamos la componente 1 de `C_slice`:

In [42]:
C_slice[1] = 12345
C_slice

array([   12, 12345,    12])

Pero la componente 1 de `C_slice` es en realidad la componente 6 de `C`, así que `C` ha cambiado:

In [43]:
C

array([    0,     2,     4,     6,     8,    12, 12345,    12,    16,
          18])

Podemos incluso cambiar toda la subsecuencia, cambiando así es parte del array original:

In [44]:
C_slice[:] = 64
C

array([ 0,  2,  4,  6,  8, 64, 64, 64, 16, 18])

Nótese la diferencia con las listas de python, en las que `l[:]` es la manera estándar de crear una *copia* de una lista `l`. En el caso de *numpy*, si se quiere realizar una copia, se ha de usar el método `copy` (por ejemplo, `C.copy()`).

**Arrays de más dimensiones**

El acceso a los componentes de arrays de dos o más dimensiones es similar, aunque la casuística es más variada.

Cuando accedemos con un único índice, estamos accediendo al correspondiente subarray de esa posición. Por ejemplo, en array de dos dimensiones, con 3 filas y 3 columnas, la posición 2 es la tercera fila:

In [45]:
C2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C2d[2]

array([7, 8, 9])

De esta manera, recursivamente, podríamos acceder a los componentes individuales de una array de cualquier dimensión. En el ejemplo anterior, el elemento de la primera fila y la tercera columna sería:

In [46]:
C2d[0][2]

3

Normalmente no se suele usar la notación anterior para acceder a los elementos individuales, sino que se usa un único corchete con los índices separados por comas: Lo siguiente es equivalente:

In [47]:
C2d[0, 2]

3

Veamos más ejemplos de acceso y modificación en arrays multidimensionales, en este caso con tres dimensiones.

In [48]:
C3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Accediendo a la posición 0 obtenemos el correspondiente subarray de dos dimensiones:

In [49]:
C3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Vamos a guardar una copia de de ese subarray y lo modificamos en el original con el número `42` en todas las posiciones:

In [50]:
old_values = C3d[0].copy()
C3d[0] = 42
C3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Y ahora reestablecemos los valores originales:

In [51]:
C3d[0] = old_values
C3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Como antes, podemos en este array de tres adimensiones acceder a una de sus componentes, especificando los tres índices: 

In [52]:
C3d[1,0,2]

9

Si sólo especificamos dos de los tres índices, accedemos al correspondiente subarray unidimensional:

In [53]:
C3d[1, 0]

array([7, 8, 9])

#### Indexado usando *slices*

In [54]:
C2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Los *slicings* en arrays multidimensionales se hacen a lo largo de los correspondientes ejes. Por ejemplo, en un array bidimensional, lo haríamos sobre la secuencia de filas. 

In [55]:
C2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Pero también podríamos hacerlo en ambos ejes. Por ejemplo para obtener el subarray hasta la segunda fila y a partir de la primera columna:

In [56]:
C2d[:2, 1:]

array([[2, 3],
       [5, 6]])

Si en alguno de los ejes se usa un índice individual, entonces se pierde una de las dimensiones:

In [57]:
C2d[1, :2]

array([4, 5])

Nótese la diferencia con la operación `C2d[1:2,:2]`. Puede parecer que el resultado ha de ser el mismo, pero si se usa slicing en ambos ejes se mantiene el número de dimensiones:

In [58]:
C2d[1:2,:2] # si haces slicing no baja el número de dimensiones, si haces indexado sí

array([[4, 5]])

Más ejemplos:

In [59]:
C2d[:2, 2]

array([3, 6])

In [60]:
C2d[:, :1]

array([[1],
       [4],
       [7]])

Como hemos visto más arriba, podemos usar *slicing* para asignar valores a las componentes de un array. Por ejemplo

In [61]:
C2d[:2, 1:] = 0
C2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Indexado con booleanos

Los arrays de booleanos se pueden usar en numpy como una forma de indexado para seleccionar determinadas componenetes en una serie de ejes. 

Veamos el siguiente ejemplo:

In [62]:
nombres = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [63]:
data = np.random.randn(7, 4)
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

Podríamos interpretar que cada fila del array `data` son datos asociados a las correspondientes personas del array `nombres`. Si ahora queremos quedarnos por ejemplos con las filas correspondientes a Bob, podemos usar indexado booleano de la siguiente manera:

El array de booleanos que vamos a usar será:

In [64]:
nombres == 'Bob'

array([ True, False, False,  True, False, False, False])

Y el indexado con ese array, en el eje de las filas, nos dará el subarray de las filas correspondientes a Bob:

In [65]:
data[nombres == 'Bob']

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

Podemos mezclar indexado booleano con índices concretos o con slicing en distintos ejes:

In [66]:
data[nombres == 'Bob', 2:]

array([[ 0.769 ,  1.2464],
       [-0.5397,  0.477 ]])

In [67]:
data[nombres == 'Bob', 3]

array([1.2464, 0.477 ])

Para usar el indexado complementario (en el ejemplo, las filas correspondientes a las personas que no son Bob), podríamos usar el array de booleanos `nombres != 'Bob'`. Sin embargo, es más habitual usar el operador `~`:

In [68]:
data[~(nombres == 'Bob')]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

Incluso podemos jugar con otros operadores booleanos como `&` (and) y `|` (or), para construir indexados booleanos que combinan condiciones. 

Por ejemplo, para obtener las filas correspondiente a Bob o a Will:

In [69]:
mask = (nombres == 'Bob') | (nombres == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241]])

Y como en los anteriores indexados, podemos usar el indexado booleano para modificar componentes de los arrays. Lo siguiente pone a 0 todos los componentes neativos de `data`:

In [71]:
data<0

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [72]:
data[data < 0] = 0
data

array([[0.0929, 0.2817, 0.769 , 1.2464],
       [1.0072, 0.    , 0.275 , 0.2289],
       [1.3529, 0.8864, 0.    , 0.    ],
       [1.669 , 0.    , 0.    , 0.477 ],
       [3.2489, 0.    , 0.    , 0.1241],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

Obsérvese que ahora `data<0` es un array de booleanos bidimensional con la misma estructura que el propio `data` y que por tanto tanto estamos haciendo indexado booleano sobre ambos ejes. 

Podríamos incluso fijar un valor a filas completas, usando indexado por un booleano unidimensional:

In [73]:
data[~(nombres == 'Joe')] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.0072, 0.    , 0.275 , 0.2289],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

### *Fancy Indexing*

El término *fancy indexing* se usa en numpy para indexado usando arrays de enteros. Veamos un ejemplo:

In [95]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Indexando con `[4,3,0,6]` nos permite obtener las filas indicadas en el orden dado:

In [96]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Si usamos más de un array para hacer *fancy indexing*, entonces toma los componentes descritos por la tupla de índices correspondiente al `zip` de los arrays de índices. Veámoslos con el siguiente ejemplo:

In [97]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [100]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Se han obtenido los elementos de índices `(1,0)`, `(5,3)`, `(7,1)` y `(2,2)`: 

Quizás en este último caso, lo "natural" sería que nos hubiera devuelto el subarray formado por las filas 1, 5, 7 y 2 (en ese orden), y de ahí solo las columnas 0, 3 , 1 y 2 (en ese orden. 

Para obtener eso debemos hacer la siguiente operación:

In [101]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Dos observaciones importantes sobre el *fancy indexing*:

* Siempre devuelve arrays unidimensionales.
* A diferencia del *slicing*, siempre construye una copia del array sobre el que se aplica (nunca una *vista*). 

### Trasposición de arrays y producto matricial

El método `T` obtiene el array traspuesto de uno dado:

In [102]:
D = np.arange(15).reshape((3, 5))
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
D.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [104]:
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

En el cálculo matricial será de mucha utilidad el método `np.dot` de numpy, que sirve tanto para calcular el producto escalar como el producto matricial. Veamos varios usos: 

In [108]:
E = np.random.randn(6, 3)
E

array([[-0.0119,  1.0048,  1.3272],
       [-0.9193, -1.5491,  0.0222],
       [ 0.7584, -0.6605,  0.8626],
       [-0.01  ,  0.05  ,  0.6702],
       [ 0.853 , -0.9559, -0.0235],
       [-2.3042, -0.6525, -1.2183]])

Ejemplos de producto escalar:

In [109]:
np.dot(E[:,0],E[:,1]) # producto escalar de dos columnas

1.5988144307734338

In [110]:
np.dot(E[2],E[4]) # producto escalar de dos filas

1.257967004991232

In [111]:
np.dot(E.T, E[:,0]) # producto de una matriz por un vector

array([7.4574, 1.5988, 3.3985])

In [112]:
np.dot(E.T,E)   # producto de dos matrices

array([[7.4574, 1.5988, 3.3985],
       [1.5988, 5.1876, 1.5803],
       [3.3985, 1.5803, 4.44  ]])

In [113]:
np.dot(E,E.T)   # producto de dos matrices

array([[ 2.7712, -1.5162,  0.4721,  0.9399, -1.0018, -2.2452],
       [-1.5162,  3.2453,  0.3452, -0.0534,  0.6961,  3.1019],
       [ 0.4721,  0.3452,  1.7555,  0.5375,  1.258 , -2.3674],
       [ 0.9399, -0.0534,  0.5375,  0.4518, -0.0721, -0.826 ],
       [-1.0018,  0.6961,  1.258 , -0.0721,  1.6418, -1.3131],
       [-2.2452,  3.1019, -2.3674, -0.826 , -1.3131,  7.2195]])

In [114]:
np.dot(E.T, E[:,:1]) # producto de dos matrices

array([[7.4574],
       [1.5988],
       [3.3985]])

## Funciones universales sobre arrays (componente a componente)

En este contexto, una función universal (o *ufunc*) es una función que actúa sobre cada componente de un array o arrays de numpy. Estas funciones son muy eficientes y se denominan *vectorizadas*. Por ejemplo:   

In [115]:
M = np.arange(10)
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.sqrt(M) # raiz cuadrada de cada componente

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [117]:
np.exp(M.reshape(2,5)) # exponencial de cad componente

array([[   1.    ,    2.7183,    7.3891,   20.0855,   54.5982],
       [ 148.4132,  403.4288, 1096.6332, 2980.958 , 8103.0839]])

Existen funciones universales que actúan sobre dos arrays, ya que realizan operaciones binarias:

In [118]:
x = np.random.randn(8)
y = np.random.randn(8)
x,y

(array([-1.3326,  1.0746,  0.7236,  0.69  ,  1.0015, -0.5031, -0.6223,
        -0.9212]),
 array([-0.7262,  0.2229,  0.0513, -1.1577,  0.8167,  0.4336,  1.0107,
         1.8249]))

In [119]:
np.maximum(x, y)

array([-0.7262,  1.0746,  0.7236,  0.69  ,  1.0015,  0.4336,  1.0107,
        1.8249])

Existe una numerosa colección de *ufuncs* tanto unarias como bianrias. Se recomienda consultar el manual. 

### Expresiones condicionales vectorizadas con *where*

Veamos cómo podemos usar un versión vectorizada de la función `if`. 

Veámoslo con un ejemplo. Supongamos que tenemos dos arrays (unidimensionales) numéricos y otro array booleano del mismo tamaño: 

In [120]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Si quisiéramos obtener el array que en cada componente tiene el valor de `xs` si el correspondiente en `cond` es `True`, o el valor de `ys` si el correspondiente en `cond` es `False`, podemos hacer lo siguiente:  

In [121]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

Sin embargo, esto tiene dos problemas: no es lo suficientemente eficiente, y además no se traslada bien a arrays multidimensionales. Afortunadamente, tenemos `np.where` para hacer esto de manera conveniente:

In [122]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

No necesariamente el segundo y el tercer argumento tiene que ser arrays. Por ejemplo:

In [123]:
F = np.random.randn(4, 4)

F,np.where(F > 0, 2, -2)

(array([[-0.9975,  0.8506, -0.1316,  0.9124],
        [ 0.1882,  2.1695, -0.1149,  2.0037],
        [ 0.0296,  0.7953,  0.1181, -0.7485],
        [ 0.585 ,  0.1527, -1.5657, -0.5625]]),
 array([[-2,  2, -2,  2],
        [ 2,  2, -2,  2],
        [ 2,  2,  2, -2],
        [ 2,  2, -2, -2]]))

O una combinación de ambos. Por ejemplos, para modificar sólo las componentes positivas:

In [124]:
np.where(F > 0, 2, F) 

array([[-0.9975,  2.    , -0.1316,  2.    ],
       [ 2.    ,  2.    , -0.1149,  2.    ],
       [ 2.    ,  2.    ,  2.    , -0.7485],
       [ 2.    ,  2.    , -1.5657, -0.5625]])

### Funciones estadísticas

Algunos métodos para calcular indicadores estadísticos sobre los elementos de un array.

* `np.sum`: suma de los componentes
* `np.mean`: media aritmética
* `np.std` y `np.var`: desviación estándar y varianza, respectivamente.
* `np.max` y `np.min`: máximo y mínimo, resp.
* `np.argmin` y `np.argmax`: índices de los mínimos o máximos elementos, respectivamente.
* `np.cumsum`: sumas acumuladas de cada componente

Estos métodos también se pueden usar como atributos de los arrays. Es decir, por ejemplo `A.sum()` o `A.mean()`.

Veamos algunos ejemplos, generando en primer lugar un array con elementos generados aleatoriamente (siguiendo una distribución normal):

In [125]:
G = np.random.randn(5, 4)
G

array([[-0.0327, -0.929 , -0.4826, -0.0363],
       [ 1.0954,  0.9809, -0.5895,  1.5817],
       [-0.5287,  0.457 ,  0.93  , -1.5693],
       [-1.0225, -0.4028,  0.2205, -0.1934],
       [ 0.6692, -1.649 , -2.2528, -1.1668]])

In [126]:
G.sum()

-4.9206947817910605

In [127]:
G.mean()

-0.24603473908955303

In [128]:
G.cumsum() # por defecto, se aplana el array y se hace la suma acumulada

array([-0.0327, -0.9617, -1.4442, -1.4805, -0.3851,  0.5958,  0.0063,
        1.588 ,  1.0593,  1.5163,  2.4463,  0.877 , -0.1455, -0.5483,
       -0.3278, -0.5212,  0.1479, -1.5011, -3.7539, -4.9207])

Todas estas funciones se pueden aplicar a lo largo de un eje, usando el parámetro `axis`. Por ejemplos, para calcular las medias de cada fila (es decir, recorriendo en el sentido de las columnas), aplicamos `mean` por `axis=1`:

In [129]:
G.mean(axis=1)

array([-0.3701,  0.7671, -0.1778, -0.3496, -1.0999])

Y la suma de cada columna (es decir, recorriendo las filas), con `sum` por `axis=0`:

In [130]:
G.sum(axis=0)

array([ 0.1807, -1.5429, -2.1744, -1.3841])

Suma acumulada de cada columna:

In [131]:
G.cumsum(axis=0)

array([[-0.0327, -0.929 , -0.4826, -0.0363],
       [ 1.0627,  0.0519, -1.0721,  1.5454],
       [ 0.534 ,  0.5089, -0.1421, -0.0238],
       [-0.4885,  0.1061,  0.0784, -0.2172],
       [ 0.1807, -1.5429, -2.1744, -1.3841]])

Dentro de cada columna, el número de fila donde se alcanza el mínimo se puede hacer asi:

In [132]:
G,G.argmin(axis=0)

(array([[-0.0327, -0.929 , -0.4826, -0.0363],
        [ 1.0954,  0.9809, -0.5895,  1.5817],
        [-0.5287,  0.457 ,  0.93  , -1.5693],
        [-1.0225, -0.4028,  0.2205, -0.1934],
        [ 0.6692, -1.649 , -2.2528, -1.1668]]),
 array([3, 4, 4, 2]))

### Métodos para arrays booleanos

In [133]:
H = np.random.randn(50)
H

array([ 0.3536,  0.7021, -0.2746, -0.1391,  0.1077, -0.6065, -0.4171,
       -0.017 , -1.2241, -1.8008,  1.6347,  0.989 ,  0.4579,  0.5552,
        1.3067, -0.4406, -0.3014,  0.4988, -0.824 ,  1.3206,  0.508 ,
       -0.6534,  0.187 , -0.3917, -0.2723, -0.0171,  0.6803,  0.6355,
       -0.7572,  0.7181, -0.3043, -1.6778,  0.427 , -1.5637, -0.3675,
        1.0459,  1.22  , -0.2477, -0.4162, -0.1167, -1.8448,  2.0687,
       -0.777 ,  1.4402, -0.1106,  1.2274,  1.9208,  0.7464,  2.2247,
       -0.6794])

Es bastante frecuente usar `sum` para ontar el número de veces que se cumple una condición en un array, aprovechando que `True` se identifica con 1 y `False` con 0:

In [134]:
(H > 0).sum() # Number of positive values

24

Las funciones python `any` y `all` tienen también su correspondiente versión vectorizada. `any` se puede ver como un *or* generalizado, y `all`como un *and* generalizado:  

In [3]:
bools = np.array([False, False, True, False])
bools.any(),bools.all()

TypeError: an integer is required

Podemos comprobar si se cumple *alguna vez* una condición entre los componentes de un array, o bien si se cumple *siempre* una condición:

In [136]:
np.any(H>0)

True

In [137]:
np.all(H< 10)

True

In [138]:
np.any(H > 15)

False

In [139]:
np.all(H >0)

False

## Entrada y salida de arrays en ficheros

Existen una serie de utilidades para guardar el contenido de un array en un fichero y recuperarlo más tarde. 

Las funciones `save` y `load` hacen esto. Los arrays se almacenan en archivos con extensión *npy*.  

In [140]:
J = np.arange(10)
np.save('un_array', J)

In [141]:
np.load('un_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Con `savez`, podemos guardar una serie de arrays en un archivo de extensión *npz*, asociados a una serie de claves. Por ejemplo:

In [142]:
np.savez('array_archivo.npz', a=J, b=J**2)

Cuando hacemos `load` sobre un archivo *npz*, cargamos un objeto de tipo diccionario, con el que podemos acceder (de manera perezosa) a los distintos arrays que se han almacenado:

In [143]:
arch = np.load('array_archivo.npz')
arch['b']

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [144]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

En caso de que fuera necesario, podríamos incluso guardar incluso los datos en formato comprimido con `savez_compressed`:

In [145]:
np.savez_compressed('arrays_comprimidos.npz', a=arr, b=arr)

In [146]:
!rm un_array.npy
!rm array_archivo.npz
!rm arrays_comprimidos.npz

In [147]:
m = np.random.randn(3,4)



maximo = m.max()



minimo = m.min()



normalizada = (m-minimo) / (maximo - minimo)



m,normalizada

(array([[ 0.7274, -0.8687, -1.2139, -0.4706],
        [-0.9192, -0.8388,  0.4352, -0.5578],
        [-0.5675, -0.3726, -0.9266,  1.7551]]),
 array([[0.6538, 0.1162, 0.    , 0.2503],
        [0.0992, 0.1263, 0.5554, 0.221 ],
        [0.2177, 0.2833, 0.0968, 1.    ]]))